default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: db
test:
  <<: *default
  database: ${APP_NAME}_test
development:
  <<: *default
  database: ${APP_NAME}_development
