version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - containers/${RAILS_ENV}/.env
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: containers/${RAILS_ENV}/Dockerfile
    env_file:
      - containers/${RAILS_ENV}/.env
    command: containers/scripts/wait-for-it.sh db:3306 -- containers/${RAILS_ENV}/entrypoint
    depends_on:
      - db
    volumes:
      - .:/usr/app/${APP_NAME}
    volumes_from:
      - box
    ports:
      - 3000:3000
  box:
    image: busybox
    volumes:
      - /box
