#!/bin/bash
set -e
if [[ -a /tmp/puma.pid ]]; then
  rm /tmp/puma.pid
fi
bundle install --without development test -j4
bundle exec rake db:create
bundle exec rake db:migrate
if [[ \$RAILS_ENV == "production" ]]; then
  # rake assets:precompile
  mkdir -p /etc/nginx/conf.d/
  cp -rf containers/${RAILS_ENV}/nginx.conf /etc/nginx/conf.d/default.conf
  cp -rf containers/${RAILS_ENV}/server.csr /etc/nginx/conf.d/server.csr
  cp -rf containers/${RAILS_ENV}/server.key /etc/nginx/conf.d/server.key
fi

rails server -b 0.0.0.0 -P /tmp/puma.pid
exec "\$@"
