#!/bin/bash
set -e
if [[ -a /tmp/puma.pid ]]; then
  rm /tmp/puma.pid
fi
bundle install --without development test -j4
bundle exec rake db:create
bundle exec rake db:migrate
if [[ \$RAILS_ENV == "production" ]]; then
  # rake assets:precompile
  mkdir -p /etc/nginx/conf.d/
  cp containers/${RAILS_ENV}/nginx.conf /etc/nginx/conf.d/default.conf
  cp containers/${RAILS_ENV}/nginx.pem /etc/nginx/ssl/nginx.pem
  cp containers/${RAILS_ENV}/key.pem /etc/nginx/ssl/key.pem
fi

rails server -b 0.0.0.0 -P /tmp/puma.pid
exec "\$@"
